from Car import Car
from CarsList import CarsList
carsList = CarsList()
def bord(level):
    if level == 1:
        width = 6
        exit = 22
        RedCar = Car(21, True, 2)
        Car1 = Car(0, False, 2)
        Car2 = Car(7, True, 2)
        Car3 = Car(3, False, 2)
        Car4 = Car(4, True, 2)
        Car5 = Car(16, True, 2)
        Car6 = Car(33, True, 2)
        Car7 = Car(20, False, 2)
        Car8 = Car(23, False, 3)
        carsList.cars.append(Car1) # hoe moet ik hier appenden???? carslist.cars.append(Car1) ?? waarom cars
        carsList.cars.append(Car2)
        carsList.cars.append(Car3)
        carsList.cars.append(Car4)
        carsList.cars.append(Car5)
        carsList.cars.append(Car6)
        carsList.cars.append(Car7)
        carsList.cars.append(Car8)
        carsList.cars.append(RedCar)
        return [carsList,width,exit]
    elif level == 2:
        width = 6
        exit = 22
        RedCar = Car(20, True, 2)
        Car1 = Car(0, False, 2)
        Car2 = Car(12, True, 2)
        Car3 = Car(3, False, 2)
        Car4 = Car(4, True, 2)
        Car5 = Car(10, True, 2)
        Car6 = Car(14, True, 2)
        Car7 = Car(16, False, 2)
        Car8 = Car(17, False, 3)
        Car9 = Car(25, True, 2)
        Car10 = Car(27, True, 2)
        Car11 = Car(32, True, 2)
        Car12 = Car(34, True, 2)
        carsList.cars.append(Car1)
        carsList.cars.append(Car2)
        carsList.cars.append(Car3)
        carsList.cars.append(Car4)
        carsList.cars.append(Car5)
        carsList.cars.append(Car6)
        carsList.cars.append(Car7)
        carsList.cars.append(Car8)
        carsList.cars.append(Car9)
        carsList.cars.append(Car10)
        carsList.cars.append(Car11)
        carsList.cars.append(Car12)
        carsList.cars.append(RedCar)
        return [carsList,width,exit]
    elif level == 3:
        width = 6
        exit = 22
        RedCar = Car(18, True, 2)
        Car1 = Car(0, False, 2)
        Car2 = Car(12, True, 2)
        Car3 = Car(2, False, 2)
        Car4 = Car(10, True, 2)
        Car5 = Car(14, True, 2)
        Car6 = Car(16, False, 2)
        Car7 = Car(17, False, 3)
        Car8 = Car(25, True, 2)
        Car9 = Car(27, True, 2)
        Car10 = Car(32, True, 2)
        Car11 = Car(34, True, 2)
        carsList.cars.append(Car1)
        carsList.cars.append(Car2)
        carsList.cars.append(Car3)
        carsList.cars.append(Car4)
        carsList.cars.append(Car5)
        carsList.cars.append(Car6)
        carsList.cars.append(Car7)
        carsList.cars.append(Car8)
        carsList.cars.append(Car9)
        carsList.cars.append(Car10)
        carsList.cars.append(Car11)
        carsList.cars.append(RedCar)
        return [carsList,width,exit]
    elif level == 4: # werkt nog niet!
        width = 9
        exit = 43
        RedCar = Car(37, True, 2)
        Car1 = Car(0, False, 2)
        Car2 = Car(1, True, 3)
        Car3 = Car(4, False, 2)
        Car4 = Car(5, True, 2)
        Car5 = Car(7, True, 2)
        Car6 = Car(11, False, 3)
        Car7 = Car(12, False, 2)
        Car8 = Car(17, False, 3)
        Car9 = Car(18, True, 2)
        Car10 = Car(22, True, 2)
        Car11 = Car(27, False, 2)
        Car12 = Car(45, True, 2)
        Car13 = Car(48, False, 3)
        Car14 = Car(44, False, 3)
        Car15 = Car(30, False, 2)
        Car16 = Car(59, False, 3)
        Car17 = Car(32, True, 3)
        Car18 = Car(63, False, 2)
        Car19 = Car(73, True, 3)
        Car20 = Car(50, True, 3)
        Car21 = Car(69, True, 3)
        carsList.cars.append(Car1)
        carsList.cars.append(Car2)
        carsList.cars.append(Car3)
        carsList.cars.append(Car4)
        carsList.cars.append(Car5)
        carsList.cars.append(Car6)
        carsList.cars.append(Car7)
        carsList.cars.append(Car8)
        carsList.cars.append(Car9)
        carsList.cars.append(Car10)
        carsList.cars.append(Car11)
        carsList.cars.append(Car12)
        carsList.cars.append(Car13)
        carsList.cars.append(Car14)
        carsList.cars.append(Car15)
        carsList.cars.append(Car16)
        carsList.cars.append(Car17)
        carsList.cars.append(Car18)
        carsList.cars.append(Car19)
        carsList.cars.append(Car20)
        carsList.cars.append(Car21)
        carsList.cars.append(RedCar)
        return [carsList,width,exit]
    elif level == 5:
        width = 9
        exit = 43
        RedCar = Car(42, True, 2)
        Car1 = Car(0, False, 2)
        Car2 = Car(1, False, 2)
        Car3 = Car(18, False, 2)
        Car4 = Car(2, True, 2)
        Car5 = Car(11, True, 2)
        Car6 = Car(4, False, 2)
        Car7 = Car(14, True, 3)
        Car8 = Car(8, False, 2)
        Car9 = Car(20, False, 2)
        Car10 = Car(21, True, 2)
        Car11 = Car(23, False, 3)
        Car12 = Car(24, True, 2)
        Car13 = Car(26, False, 3)
        Car14 = Car(38, True, 3)
        Car15 = Car(49, True, 2)
        Car16 = Car(51, False, 2)
        Car17 = Car(52, True, 2)
        Car18 = Car(57, False, 3)
        Car19 = Car(58, True, 2)
        Car20 = Car(72, True, 3)
        Car21 = Car(68, False, 2)
        Car22 = Car(69, False, 2)
        Car23 = Car(70, True, 2)
        carsList.cars.append(Car1)
        carsList.cars.append(Car2)
        carsList.cars.append(Car3)
        carsList.cars.append(Car4)
        carsList.cars.append(Car5)
        carsList.cars.append(Car6)
        carsList.cars.append(Car7)
        carsList.cars.append(Car8)
        carsList.cars.append(Car9)
        carsList.cars.append(Car10)
        carsList.cars.append(Car11)
        carsList.cars.append(Car12)
        carsList.cars.append(Car13)
        carsList.cars.append(Car14)
        carsList.cars.append(Car15)
        carsList.cars.append(Car16)
        carsList.cars.append(Car17)
        carsList.cars.append(Car18)
        carsList.cars.append(Car19)
        carsList.cars.append(Car20)
        carsList.cars.append(Car21)
        carsList.cars.append(Car22)
        carsList.cars.append(Car23)
        carsList.cars.append(RedCar)
        return [carsList,width,exit]
    elif level == 6:
        width = 9
        exit = 43
        RedCar = Car(36, True, 2)
        Car1 = Car(0, False, 3)
        Car2 = Car(1, True, 3)
        Car3 = Car(4, False, 3)
        Car4 = Car(11, True, 2)
        Car5 = Car(14, True, 2)
        Car6 = Car(17, False,3)
        Car7 = Car(19, False, 2)
        Car8 = Car(20, True, 2)
        Car9 = Car(23, True, 3)
        Car10 = Car(30, False, 3)
        Car11 = Car(31, True, 2)
        Car12 = Car(33, True, 2)
        Car13 = Car(38, False, 2)
        Car14 = Car(49, False, 2)
        Car15 = Car(50, False, 2)
        Car16 = Car(51, True, 3)
        Car17 = Car(54, False, 2)
        Car18 = Car(56, True, 2)
        Car19 = Car(61, True, 2)
        Car20 = Car(64, True, 3)
        Car21 = Car(67, False, 2)
        Car22 = Car(68,True, 2)
        Car23 = Car(70, False, 2)
        Car24 = Car(72,True,2)
        Car25 = Car(74,True,2)
        carsList.cars.append(Car1)
        carsList.cars.append(Car2)
        carsList.cars.append(Car3)
        carsList.cars.append(Car4)
        carsList.cars.append(Car5)
        carsList.cars.append(Car6)
        carsList.cars.append(Car7)
        carsList.cars.append(Car8)
        carsList.cars.append(Car9)
        carsList.cars.append(Car10)
        carsList.cars.append(Car11)
        carsList.cars.append(Car12)
        carsList.cars.append(Car13)
        carsList.cars.append(Car14)
        carsList.cars.append(Car15)
        carsList.cars.append(Car16)
        carsList.cars.append(Car17)
        carsList.cars.append(Car18)
        carsList.cars.append(Car19)
        carsList.cars.append(Car20)
        carsList.cars.append(Car21)
        carsList.cars.append(Car22)
        carsList.cars.append(Car23)
        carsList.cars.append(Car24)
        carsList.cars.append(Car25)
        carsList.cars.append(RedCar)
        return [carsList,width,exit]
    elif level == 7:
        width = 12
        exit = 82
        RedCar = Car(74, True, 2)
        Car1 = Car(1, True, 2)
        Car2 = Car(3, True, 3)
        Car3 = Car(6, False, 3)
        Car4 = Car(7, True, 2)
        Car5 = Car(9, False, 2)
        Car6 = Car(10, False,3)
        Car7 = Car(11, False, 2)
        Car8 = Car(26, False, 2)
        Car9 = Car(27, True, 3)
        Car10 = Car(32, True, 2)
        Car11 = Car(35, False, 2)
        Car12 = Car(36, True, 2)
        Car13 = Car(39, True, 3)
        Car14 = Car(42, False, 3)
        Car15 = Car(43, True, 3)
        Car16 = Car(48, True, 3)
        Car17 = Car(51, False, 2)
        Car18 = Car(52, True, 2)
        Car19 = Car(55,False, 2)
        Car20 = Car(57, False, 2)
        Car21 = Car(58, True, 2)
        Car22 = Car(60,True, 3)
        Car23 = Car(64, False, 2)
        Car24 = Car(65,False,2)
        Car25 = Car(70, True,2)
        Car26 = Car(72, False, 3)
        Car27 = Car(73, False, 3)
        Car28 = Car(86, True, 3)
        Car29 = Car(89, False, 2)
        Car30 = Car(90, False,3)
        Car31 = Car(91, True, 3)
        Car32 = Car(103, True, 2)
        Car33 = Car(105, True, 2)
        Car34 = Car(108, True, 3)
        Car35 = Car(111, True, 2)
        Car36 = Car(113, False, 2)
        Car37 = Car(115, True, 2)
        Car38 = Car(118, False, 2)
        Car39 = Car(119, False, 2)
        Car40 = Car(120, False, 2)
        Car41 = Car(126, False, 2)
        Car42 = Car(139, True, 3)
        Car43 = Car(142, True, 2)
        carsList.cars.append(Car1)
        carsList.cars.append(Car2)
        carsList.cars.append(Car3)
        carsList.cars.append(Car4)
        carsList.cars.append(Car5)
        carsList.cars.append(Car6)
        carsList.cars.append(Car7)
        carsList.cars.append(Car8)
        carsList.cars.append(Car9)
        carsList.cars.append(Car10)
        carsList.cars.append(Car11)
        carsList.cars.append(Car12)
        carsList.cars.append(Car13)
        carsList.cars.append(Car14)
        carsList.cars.append(Car15)
        carsList.cars.append(Car16)
        carsList.cars.append(Car17)
        carsList.cars.append(Car18)
        carsList.cars.append(Car19)
        carsList.cars.append(Car20)
        carsList.cars.append(Car21)
        carsList.cars.append(Car22)
        carsList.cars.append(Car23)
        carsList.cars.append(Car24)
        carsList.cars.append(Car25)
        carsList.cars.append(Car26)
        carsList.cars.append(Car27)
        carsList.cars.append(Car28)
        carsList.cars.append(Car29)
        carsList.cars.append(Car30)
        carsList.cars.append(Car31)
        carsList.cars.append(Car32)
        carsList.cars.append(Car33)
        carsList.cars.append(Car34)
        carsList.cars.append(Car35)
        carsList.cars.append(Car36)
        carsList.cars.append(Car37)
        carsList.cars.append(Car38)
        carsList.cars.append(Car39)
        carsList.cars.append(Car40)
        carsList.cars.append(Car41)
        carsList.cars.append(Car42)
        carsList.cars.append(Car43)
        carsList.cars.append(RedCar)
    elif level == 8:
        width = 9
        exit = 43
        RedCar = Car(40, True, 2)

        Car4 = Car(7, False, 2)
        Car2 = Car(61,False,3)
        Car3 = Car(25, False, 3)

        Car1 = Car(36,False,3)
        carsList.cars.append(Car1)
        carsList.cars.append(Car2)
        carsList.cars.append(Car3)
        #carsList.cars.append(Car4)
        carsList.cars.append(RedCar)
        return [carsList,width,exit]
    return [carsList,width,exit]
#print bord(2)
